import type { GeneratedStoryOutput } from './generateStoryContent'

function printValue(value: unknown, indent: number): string {
  const pad = '  '.repeat(indent)
  const next = '  '.repeat(indent + 1)

  if (value === undefined) return 'undefined'
  if (value === null) return 'null'
  if (typeof value === 'string') return JSON.stringify(value)
  if (typeof value === 'number' || typeof value === 'boolean') return String(value)

  if (Array.isArray(value)) {
    if (value.length === 0) return '[]'
    const items = value.map((item) => `${next}${printValue(item, indent + 1)},`).join('\n')
    return `[\n${items}\n${pad}]`
  }

  if (typeof value === 'object') {
    const entries = Object.entries(value as Record<string, unknown>).filter(
      ([, v]) => v !== undefined,
    )
    if (entries.length === 0) return '{}'
    const body = entries
      .map(([key, v]) => `${next}${JSON.stringify(key)}: ${printValue(v, indent + 1)},`)
      .join('\n')
    return `{\n${body}\n${pad}}`
  }

  return JSON.stringify(value)
}

export function serializeStoryDetailsTs(output: GeneratedStoryOutput): string {
  return `/**
 * GENERATED by MARARX Studio — do not edit by hand.
 * Not wired into the live public site. Inspect only.
 * Generated: ${output.generatedAt}
 * Slug: ${output.slug}
 */
import type { StoryContentBlock } from '../../src/data/story-details'

export const generatedStoryContent: StoryContentBlock[] = ${printValue(output.blocks, 0)}
`
}

export function serializeStoriesEntryTs(output: GeneratedStoryOutput): string {
  return `/**
 * GENERATED by MARARX Studio — do not edit by hand.
 * Not wired into the live public site. Inspect only.
 * Generated: ${output.generatedAt}
 * Slug: ${output.slug}
 */
import type { StoryPreview } from '../../src/data/stories'

export const generatedStoryPreview = ${printValue(output.preview, 0)} as StoryPreview & { route?: string }
`
}

export function serializeGeneratedJson(output: GeneratedStoryOutput): string {
  return `${JSON.stringify(output, null, 2)}\n`
}

export function buildGeneratedFilenames(slug: string) {
  return {
    details: `${slug}.story-details.generated.ts`,
    preview: `${slug}.stories-entry.generated.ts`,
    json: `${slug}.generated.json`,
  }
}
